#!/usr/bin/env python3
"""
Generates hotkeys.js (the file installer.sh concatenates onto main.js — see main.js's own header
comment for why that concatenation happens at install time rather than a runtime #include) from
hotkeys.json, a structured config the web UI (shared/hotkeys-ui.html) edits.

Binding "type" maps to one main.js function each:
  windowCycle / windowToggle -> manageAppWindows(resourceClass, mode, launchArgv)
  profileCycle                -> cycleChromiumProfile(resourceClass, profileName)
  tabFocus                    -> focusTab(resourceClass, profileName, urlPatterns, openUrl)

Once hotkeys.json has been saved via the UI, it — not hand-edited hotkeys.js — is the source of
truth: every save regenerates hotkeys.js from scratch, so direct edits to hotkeys.js won't
survive the next UI save. hotkeys.js remains fully hand-editable on its own for anyone who never
touches the UI at all; nothing here runs unless something calls generate_hotkeys_js.
"""

import json

GENERATED_HEADER = (
    "// Generated by the AltTabSucks hotkeys UI (shared/hotkeys-ui.html) from hotkeys.json.\n"
    "// Hand edits here will be overwritten the next time you save in the UI — edit\n"
    "// hotkeys.json (or just use the UI) instead, unless you never use the UI at all.\n"
)


def _js_string(value) -> str:
    """A JS string literal for value. json.dumps's escaping happens to be a valid JS string
    literal too (both escape quotes/backslashes/control chars the same way) — reused rather than
    hand-rolled to avoid getting that subtly wrong."""
    return json.dumps(str(value))


def _js_array_of_strings(values) -> str:
    return "[" + ", ".join(_js_string(v) for v in values) + "]"


def generate_binding_js(binding: dict) -> str:
    """Returns one registerShortcut(...) statement for a single binding dict. Raises ValueError
    on a missing/invalid field — callers should validate before this is reached in a save flow
    (see alttabsucks_server.py's POST /hotkeys-config), but this stays strict rather than silently
    emitting broken JS."""
    kind = binding.get("type")
    title = (binding.get("title") or "").strip()
    key = (binding.get("key") or "").strip()
    resource_class = (binding.get("resourceClass") or "").strip()

    if not title:
        raise ValueError(f"binding missing title: {binding!r}")
    if not key:
        raise ValueError(f"binding {title!r} missing key")
    if not resource_class:
        raise ValueError(f"binding {title!r} missing resourceClass")

    header = (
        f"registerShortcut({_js_string(title)}, {_js_string('AltTabSucks: ' + title)},\n"
        f"    {_js_string(key)}, function () {{ "
    )

    if kind in ("windowCycle", "windowToggle"):
        mode = "cycle" if kind == "windowCycle" else "toggle"
        launch_argv = binding.get("launchArgv") or []
        call = f"manageAppWindows({_js_string(resource_class)}, {_js_string(mode)}"
        if launch_argv:
            call += f", {_js_array_of_strings(launch_argv)}"
        call += ");"
    elif kind == "profileCycle":
        profile = (binding.get("profileName") or "").strip()
        if not profile:
            raise ValueError(f"binding {title!r} missing profileName")
        call = f"cycleChromiumProfile({_js_string(resource_class)}, {_js_string(profile)});"
    elif kind == "tabFocus":
        profile = (binding.get("profileName") or "").strip()
        url_patterns = binding.get("urlPatterns") or []
        open_url = (binding.get("openUrl") or "").strip()
        if not profile:
            raise ValueError(f"binding {title!r} missing profileName")
        if not url_patterns:
            raise ValueError(f"binding {title!r} missing urlPatterns")
        if not open_url:
            raise ValueError(f"binding {title!r} missing openUrl")
        call = (
            f"focusTab({_js_string(resource_class)}, {_js_string(profile)}, "
            f"{_js_array_of_strings(url_patterns)}, {_js_string(open_url)});"
        )
    else:
        raise ValueError(f"binding {title!r} has unknown type: {kind!r}")

    return header + call + " });"


def generate_hotkeys_js(config: dict) -> str:
    bindings = config.get("bindings", [])
    parts = [GENERATED_HEADER, ""]
    for binding in bindings:
        parts.append(generate_binding_js(binding))
        parts.append("")
    return "\n".join(parts)
