// Generated by the AltTabSucks hotkeys UI (shared/hotkeys-ui.html) from hotkeys.json.
// Hand edits here will be overwritten the next time you save in the UI — edit
// hotkeys.json (or just use the UI) instead, unless you never use the UI at all.


registerShortcut("Hotkey config", "AltTabSucks: Hotkey config",
    "Ctrl+Alt+/", function () { focusTab("brave-browser", "Personal", ["localhost:9876/hotkeys-ui"], "http://localhost:9876/hotkeys-ui"); });

registerShortcut("GPU dashboard", "AltTabSucks: GPU dashboard",
    "Ctrl+Alt+Shift+|", function () { focusTab("brave-browser", "Personal", ["http://localhost:8081/"], "http://localhost:8081"); });

registerShortcut("Gmail", "AltTabSucks: Gmail",
    "Ctrl+Alt+Shift+G", function () { focusTab("brave-browser", "Personal", ["mail.google.com"], "https://mail.google.com"); });

registerShortcut("Youtube", "AltTabSucks: Youtube",
    "Ctrl+Alt+Shift+Y", function () { focusTab("brave-browser", "Personal", ["youtube.com"], "https://youtube.com"); });

registerShortcut("maps", "AltTabSucks: maps",
    "Ctrl+Alt+Shift+M", function () { focusTab("brave-browser", "Personal", ["google.com/maps"], "https://google.com/maps"); });

registerShortcut("yt music", "AltTabSucks: yt music",
    "Ctrl+Shift+Meta+Y", function () { focusTab("brave-browser", "Personal", ["https://music.youtube.com"], "https://music.youtube.com"); });

registerShortcut("keep", "AltTabSucks: keep",
    "Ctrl+Shift+Meta+K", function () { focusTab("brave-browser", "Personal", ["https://keep.google.com"], "https://keep.google.com"); });

registerShortcut("chat", "AltTabSucks: chat",
    "Ctrl+Alt+Shift+C", function () { focusTab("brave-browser", "Personal", ["https://chat.google.com"], "https://chat.google.com"); });

registerShortcut("android messages", "AltTabSucks: android messages",
    "Ctrl+Alt+Shift+X", function () { focusTab("brave-browser", "Personal", ["https://messages.google.com"], "https://messages.google.com"); });

registerShortcut("ebay", "AltTabSucks: ebay",
    "Ctrl+Alt+Shift+P", function () { focusTab("brave-browser", "Personal", ["https://ebay.com"], "https://ebay.com"); });

registerShortcut("Cycle personal", "AltTabSucks: Cycle personal",
    "Ctrl+Shift+Alt+I", function () { cycleChromiumProfile("brave-browser", "Personal"); });

registerShortcut("discord", "AltTabSucks: discord",
    "Ctrl+Alt+Shift+D", function () { manageAppWindows("discord", "cycle", ["discord"]); });

registerShortcut("vscode", "AltTabSucks: vscode",
    "Ctrl+Alt+Shift+E", function () { manageAppWindows("code-oss", "cycle", ["code-oss"]); });

registerShortcut("Split browser tab", "AltTabSucks: Split browser tab",
    "Alt+X", function () { splitFocusedTab("brave-browser", "Personal"); });

registerShortcut("Merge browser tab", "AltTabSucks: Merge browser tab",
    "Alt+Z", function () { mergeFocusedWindow("brave-browser", "Personal"); });

registerShortcut("Kate", "AltTabSucks: Kate",
    "Ctrl+Alt+Shift+N", function () { manageAppWindows("org.kde.kate", "cycle", ["kate"]); });
